### ISSUE TITLE
CIRIquant test fails since commit 72dd514, PR #104

### ISSUE THREAD

**Issue by MariekeVromman** [nf-core/circrna#108]
### Description of the bug

I'm running into a ciriquant error since #104, specifically after this [commit 72dd514](https://github.com/nf-core/circrna/commit/72dd514cc90d19797bf3869b9427d879677582f6).

Reproducible by checking out that commit and running the test data
`git checkout 72dd514cc90d19797bf3869b9427d879677582f6`
`nextflow run circrna -profile test,docker,arm --tool ciriquant`

Error:
` Traceback (most recent call last):
    File "/usr/local/bin/CIRIquant", line 10, in <module>
      sys.exit(main())
    File "/usr/local/lib/python2.7/site-packages/CIRIquant/main.py", line 89, in main
      config = check_config(check_file(args.config_file))
    File "/usr/local/lib/python2.7/site-packages/CIRIquant/utils.py", line 107, in check_config
      raise ConfigError('Could not find hisat2 index with suffix: *.[1-8].ht2 or *.[1-8].ht2l, please check your configuration')
  CIRIquant.utils.ConfigError: Could not find hisat2 index with suffix: *.[1-8].ht2 or *.[1-8].ht2l, please check your configuration`

When reverting back to commit `c4a3e8e` (one commit earlier), this error does not occur, and the CIRCRNA_DISCOVERY:CIRIQUANT processes end successfully. (Another error occurs later in the pipeline but I think this is not important here.)

@nictru , tagging you as you might have a better understanding of the changes :)

**Comment by MariekeVromman** [comment]
I tried to look a bit closer at this bug. It's a bit annoying to reproduce as there are multiple bugs (some of which are already resolved in the newer version of the pipeline). But I think it comes down to this:

Before commit [72dd514](https://github.com/nf-core/circrna/commit/72dd514cc90d19797bf3869b9427d879677582f6), the creation of the yaml file included this 

in script:
`hisat2_prefix = fasta.toString() - ~/.(fa|fasta)$/`

and then further
`printf "name: ciriquant\ntools:\n  bwa: \$BWA\n  hisat2: \$HISAT2\n  stringtie: \$STRINGTIE\n  samtools: \$SAMTOOLS\n\nreference:\n  fasta: ${fasta_path}\n  gtf: ${gtf_path}\n  bwa_index: ${bwa_path}/\$BWA_FILE\n  hisat_index: ${hisat2_path}/${hisat2_prefix}" >> travis.yml`

when looking at the created file travis.yml:

`hisat_index: /Users/marieke/Documents/ciriquant/work/e4/16de17aae2f6a3e21f4454b48a54bb/hisat2/chrI`

However, with the commit commit [72dd514](https://github.com/nf-core/circrna/commit/72dd514cc90d19797bf3869b9427d879677582f6), [line 22](https://github.com/nf-core/circrna/blob/72dd514cc90d19797bf3869b9427d879677582f6/modules/local/ciriquant/yml/main.nf#L22) in this script changed to 

`hisat2_prefix = meta2.id`  taking form the input `tuple val(meta2), path(fasta)` where meta2 just contains the word `fasta` and therefore the travis.yml file then contains:

`hisat_index: /Users/marieke/Documents/ciriquant/work/e8/aebdbd37ab6875b8dfa62c0e7e9d4b/hisat2/fasta`

Which is I think the cause of the error mentioned above

**Comment by nictru** [comment]
Looks plausible, we should revert the change in line 22 in this case - thanks for pointing this out

**Comment by MariekeVromman** [comment]
ah yes, I'm just doing the PR right now :)
