### ISSUE TITLE
Unexpected error [StackOverflowError]

### ISSUE THREAD

**Issue by csittz** [nf-core/circrna#112]
Hi is there anything i need to setup before i can run this pipeline?
i can run nextflow with rnaseq image so shouldn't be nextflow installation problem.

after git clone the folder, running the test i got this error 

Linux CentOS 7

```
nextflow run circrna -profile test,docker --input circna_ss.csv --outdir result/
N E X T F L O W  ~  version 21.10.6
Launching `circrna/main.nf` [awesome_hypatia] - revision: 059337e827
WARNING: Could not load nf-core/config profiles: https://raw.githubusercontent.com/nf-core/configs/master/nfcore_custom.config
Unexpected error [StackOverflowError]
```

**Comment by nictru** [comment]
Could you try [updating nextflow](https://www.nextflow.io/docs/latest/install.html#updates) to the latest version (`23.20.1`)?

**Comment by csittz** [comment]
thanks. after updating nextflow it worked. thank you.
