### ISSUE TITLE
Process exceeded running time limit (16h)

### ISSUE THREAD

**Issue by mazzalab** [nf-core/circrna#116]
### Description of the bug

Hi again,
I've bumbed against this error with `mapsplice`. Is there a way to increase the running time limit?
I've tried with the command line below, but it seems not to respect the set limit (--max_time '240.h').

thanks in advance,
tom

```
ERROR ~ Error executing process > 'NFCORE_CIRCRNA:CIRCRNA:CIRCRNA_DISCOVERY:MAPSPLICE_ALIGN (967)'

Caused by:
  Process exceeded running time limit (16h)

Command executed:

  gzip -d -f 967_1_val_1.fq.gz
  gzip -d -f 967_2_val_2.fq.gz

  mapsplice.py \
      -c chromosomes \
      -x gencode.v45.annotation \
      -1 967_1_val_1.fq \
      -2 967_2_val_2.fq \
      -p 12 \
      --bam \
      --gene-gtf gencode.v45.annotation.gtf \
      -o 967 \
      --seglen 25 --min-intron 20 --max-intron 1000000 --min-map-len 40 --min-fusion-distance 200 --fusion-non-canonical

  cat <<-END_VERSIONS > versions.yml
  "NFCORE_CIRCRNA:CIRCRNA:CIRCRNA_DISCOVERY:MAPSPLICE_ALIGN":
      mapsplice: v2.2.1
  END_VERSIONS
```

### Command used and terminal output

```console
./nextflow run nf-core/circrna -profile docker --input samples.csv --module 'circrna_discovery' --outdir ./results_single --tool_filter 1 -r dev --fasta /data/reference_data/hg38/gome/hg38_ucsc_filtered.fa --gtf /data/reference_data/hg38/annotations/gencode.v45.annotation.gtf --mature /data/reference_data/mirBaseT/human/mature_human.fa --tool 'ciriquant,circexplorer2,find_circ,circrna_finder,mapsplice,dcc,segemehl' --bsj_reads 2 --max_time '240.h'
```

### Relevant files

[nextflow.log](https://github.com/nf-core/circrna/files/15137456/nextflow.log)

**Comment by nictru** [comment]
Hey,
you can add a `nextflow.config` file to your launch directory. This will be used without explicitly without mentioning it in the CLI call as described [here](https://www.nextflow.io/docs/latest/config.html#:~:text=nextflow.config%20in%20the%20launch%20directory). 

Within this file, you have more options for configuration than with CLI. You can for example add this:
```
process {
    withName: MAPSPLICE_ALIGN {
        time = 50.h
    }
}
```

Hope this helps!

**Comment by mazzalab** [comment]
great thanks!
