### ISSUE TITLE
FATAL:   the requested image was not found

### ISSUE THREAD

**Issue by yshen16** [nf-core/circrna#160]
### Description of the bug

when executed the command: 
`nextflow run nf-core/circrna  -profile singularity --genome GRCh37 --igenomes_base $GENOME_BASE_DIR/ref/references --outdir $OUT_DIR --input $SING_DIR/samples.csv  -r 151-error-no-genomic-sequence-available-check-g-option-error-in-gffread-command-for-task-nfcore_circrnacircrnaquantificationtranscriptome-error
`
I ran into the following error,

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name depot.galaxyproject.org-singularity-biocontainers-r-base-4.2.1.img.pulling.1721155479867 https://depot.galaxyproject.org/singularity/biocontainers/r-base:4.2.1 > /dev/null
  status : 255
  message:
    INFO:    Downloading network image
    FATAL:   the requested image was not found

### Command used and terminal output
nextflow run nf-core/circrna  -profile singularity --genome GRCh37 --igenomes_base $GENONE_BASE_DIR/ref/references --outdir $OUT_DIR --input $SING_DIR/samples.csv  -r 151-error-no-genomic-sequence-available-check-g-option-error-in-gffread-command-for-task-nfcore_circrnacircrnaquantificationtranscriptome-error

_No response_

**Comment by nictru** [comment]
This has already been solved as part of #153. Also the solution for #151 has already been merged via #157, so there is no need for using this outdated revision. Please make sure to use the latest pipeline version.
