### ISSUE TITLE
How can I accelerate the TARGETSCAN process when dealing with an excessive number of sequences that takes a long time?

### ISSUE THREAD

**Issue by xfk274280** [nf-core/circrna#164]
### Description of feature

perl /usr/local/bin/targetscan_70.pl mature.txt C23.targetscan_ts.txt C23.targetscan.txt

**Comment by nictru** [comment]
We are working on this on the `sponging` branch, we'll split the large sequence files into many smaller ones and process them independently. After that, the individual results will be aggregated to a single one. Will take 1-2 weeks till ready

**Comment by xfk274280** [comment]
Sounds like a good plan. Looking forward to seeing the improved results.

> We are working on this on the `sponging` branch, we'll split the large sequence files into many smaller ones and process them independently. After that, the individual results will be aggregated to a single one. Will take 1-2 weeks till ready

**Comment by xfk274280** [comment]
The step of miRNA prediction takes too much time, can we skip this step?

**Comment by nictru** [comment]
You can skip it by not providing `params.mature`. If you are using iGenomes, you can override the default by setting `params.mature = null` manually. The proper fix will be added later this week.
