### ISSUE TITLE
How to put the file "phenotype.csv",plesase?

### ISSUE THREAD

**Issue by bkbx** [nf-core/circrna#34]
my file and command is following:
cmd:
`nextflow run nf-core/circrna -r dev -profile docker --module 'circrna_discovery, mirna_prediction, differential_expression' --tool 'circexplorer2' --input 'samples.csv' --input_type 'fastq' --phenotype 'phenotype.csv' -resume
`
file "samples.csv" :
1C	/Work/user/ganjun/06.BYT2021070102/1C/SRR8074317.1_1.fastq.gz	/Work/user/ganjun/06.BYT2021070102/1C/SRR8074317.1_2.fastq.gz	NA
1P	/Work/user/ganjun/06.BYT2021070102/1P/SRR8074318.1_1.fastq.gz	/Work/user/ganjun/06.BYT2021070102/1P/SRR8074318.1_2.fastq.gz	NA

file "phenotype.csv"
1C	control
1P	tumor

But ,there was an error :
`[nf-core/circrna] error: 'condition' is not a column name in the phenotype file.

The response variable must be named 'condition', please refer to the usage documentation online`

Please  tell me how tu put input files .
Thanks.

**Comment by BarryDigby** [comment]
Hi there, 

You are missing the column names of both the samples.csv file and the phenotype.csv file. Please see below valid file examples: 

`samples.csv`:

```
Sample_ID,Read1,Read2,Bam
N2_rep1,results/fastq/sub/SRX9313375_T1_1.fastq,results/fastq/sub/SRX9313375_T1_2.fastq,NA
N2_rep2,results/fastq/sub/SRX9313376_T1_1.fastq,results/fastq/sub/SRX9313376_T1_2.fastq,NA
N2_rep3,results/fastq/sub/SRX9313377_T1_1.fastq,results/fastq/sub/SRX9313377_T1_2.fastq,NA
fust1_rep1,results/fastq/sub/SRX9313378_T1_1.fastq,results/fastq/sub/SRX9313378_T1_2.fastq,NA
fust1_rep2,results/fastq/sub/SRX9313379_T1_1.fastq,results/fastq/sub/SRX9313379_T1_2.fastq,NA
fust1_rep3,results/fastq/sub/SRX9313380_T1_1.fastq,results/fastq/sub/SRX9313380_T1_2.fastq,NA
```

`phenotype.csv`:

```
Sample_ID,condition
N2_rep1,N2
N2_rep2,N2
N2_rep3,N2
fust1_rep1,fust1
fust1_rep2,fust1
fust1_rep3,fust1
```

I will assume that you have more than one replicate per condition, as the differential expression module (`DESeq2`) will not run with less than 3 replicates per group. 

All the best, 

B

**Comment by bkbx** [comment]
Is the second column "condition" of file "phenotype.csv" sample_name ? not like this below ?:







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nf-core/circrna"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月13日(星期二) 晚上7:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nf-core/circrna] How to put the file "phenotype.csv",plesase? (#34)





 
Hi there,
 
You are missing the column names of both the samples.csv file and the phenotype.csv file. Please see below valid file examples:
 
samples.csv:
 Sample_ID,Read1,Read2,Bam N2_rep1,results/fastq/sub/SRX9313375_T1_1.fastq,results/fastq/sub/SRX9313375_T1_2.fastq,NA N2_rep2,results/fastq/sub/SRX9313376_T1_1.fastq,results/fastq/sub/SRX9313376_T1_2.fastq,NA N2_rep3,results/fastq/sub/SRX9313377_T1_1.fastq,results/fastq/sub/SRX9313377_T1_2.fastq,NA fust1_rep1,results/fastq/sub/SRX9313378_T1_1.fastq,results/fastq/sub/SRX9313378_T1_2.fastq,NA fust1_rep2,results/fastq/sub/SRX9313379_T1_1.fastq,results/fastq/sub/SRX9313379_T1_2.fastq,NA fust1_rep3,results/fastq/sub/SRX9313380_T1_1.fastq,results/fastq/sub/SRX9313380_T1_2.fastq,NA  
phenotype.csv:
 Sample_ID,condition N2_rep1,N2 N2_rep2,N2 N2_rep3,N2 fust1_rep1,fust1 fust1_rep2,fust1 fust1_rep3,fust1  
I will assume that you have more than one replicate per condition, as the differential expression module (DESeq2) will not run with less than 3 replicates per group.
 
All the best,
 
B

**Comment by bkbx** [comment]
Please tell me is my file "phenotype.csv" right?
samples,condition
1P,control
2P,control
3P,control
1C,tumor
2C,tumor
3C,tumor





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "浮云旧事温柔"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月15日(星期四) 上午9:05
***@***.******@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;回复： [nf-core/circrna] How to put the file "phenotype.csv",plesase? (#34)



Is the second column "condition" of file "phenotype.csv" sample_name ? not like this below ?:







------------------ 原始邮件 ------------------
发件人:                                                                                                                        "nf-core/circrna"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月13日(星期二) 晚上7:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nf-core/circrna] How to put the file "phenotype.csv",plesase? (#34)





 
Hi there,
 
You are missing the column names of both the samples.csv file and the phenotype.csv file. Please see below valid file examples:
 
samples.csv:
 Sample_ID,Read1,Read2,Bam N2_rep1,results/fastq/sub/SRX9313375_T1_1.fastq,results/fastq/sub/SRX9313375_T1_2.fastq,NA N2_rep2,results/fastq/sub/SRX9313376_T1_1.fastq,results/fastq/sub/SRX9313376_T1_2.fastq,NA N2_rep3,results/fastq/sub/SRX9313377_T1_1.fastq,results/fastq/sub/SRX9313377_T1_2.fastq,NA fust1_rep1,results/fastq/sub/SRX9313378_T1_1.fastq,results/fastq/sub/SRX9313378_T1_2.fastq,NA fust1_rep2,results/fastq/sub/SRX9313379_T1_1.fastq,results/fastq/sub/SRX9313379_T1_2.fastq,NA fust1_rep3,results/fastq/sub/SRX9313380_T1_1.fastq,results/fastq/sub/SRX9313380_T1_2.fastq,NA  
phenotype.csv:
 Sample_ID,condition N2_rep1,N2 N2_rep2,N2 N2_rep3,N2 fust1_rep1,fust1 fust1_rep2,fust1 fust1_rep3,fust1  
I will assume that you have more than one replicate per condition, as the differential expression module (DESeq2) will not run with less than 3 replicates per group.
 
All the best,
 
B

**Comment by BarryDigby** [comment]
```
Sample_ID,condition
1P,control
2P,control
3P,control
1C,tumor
2C,tumor
3C,tumor
```

as per https://nf-co.re/circrna/dev/parameters#inputoutput-options

**Comment by bkbx** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Dear master:        I'm an analysiser in China . Recently I have been using your pipeline 'nf-core/circrna' for about one month. But There occurred some problems troubling me .I 'm  expecting for your help.
        my config is below:
        my commands:nextflow run /Work/biosoft/circrna/main.nf -c /Work/biosoft/circrna/nextflow.config -profile docker --tool circexplorer2 --input samples.csv --input_type fastq --phenotype phenotype.csv -resume --outdir $PWD/resultsThe Error is below:
    
        
            
        
    Looking for your reply!Sincerely.
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                364428454
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制

**Comment by BarryDigby** [comment]
@bkbx There is no error attached to the message. Feel free to open the discussion on nf-cores slack channel, you can message me directly there. https://join.slack.com/t/nfcore/shared_invite/zt-936rglqf-ETg_2wEm5pUP59hNDXXn0A

**Comment by bkbx** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Hello! I 'm an bioinformatic analysiser in China and have been using your pipeline for a month .But there occurred some problems troubling me . I'm very expected  for your help !When I ran nextflow pipeline or ran the command by hand  , it occurred:Looking forward for your reply!Sincerely
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                364428454
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
