### ISSUE TITLE
old version of /opt/conda/envs

### ISSUE THREAD

**Issue by luciazifcakova** [nf-core/circrna#49]
Workflow execution completed unsuccessfully!
The exit status of the task that caused the workflow execution to fail was: 1.

The full error message was:

Error executing process > 'HISAT_ALIGN (eye_2)'

Caused by:
  Process `HISAT_ALIGN (eye_2)` terminated with an error exit status (1)

Command executed:

  hisat2 -p 16 --dta -q -x s_les_chr -1 FS6_S31_R1_001.fastq.gz -2 FS6_S31_R2_001.fastq.gz -t | samtools view -bS - | samtools sort --threads 16 -m 2G - > eye_2.bam

Command exit status:
  1

Command output:
  (empty)

Command error:
  Warning: the current version of HISAT2 () is older than the version (2.0.0) used to build the index.
           Users are strongly recommended to update HISAT2 to the latest version.
  Error reading _rstarts[] array: 199929, 244512
  Time loading forward index: 00:00:09
  Overall time: 00:00:09
  Error: Encountered internal HISAT2 exception (#1)
  Command: /opt/conda/envs/nf-core-circrna-1.0.0/bin/hisat2-align-s --wrapper basic-0 -p 16 --dta -q -x s_les_chr -t --read-lengths 151,150,149,148,147,35,146,145,143,141,134,131,130,126,144,140,139,138,136,117,108,90,88 -1 /tmp/2818130.inpipe1 -2 /tmp/2818130.inpipe2 
  (ERR): hisat2-align exited with value 1
  [main_samview] fail to read the header from "-".
  samtools sort: failed to read header from "-"

Work dir:
  /flash/MillerU/work/b0/ea0dc49dac2f0f89fa06090a6ad7f3

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

I run this command:
nextflow run -r mirna_rework nf-core/circrna -resume -profile singularity,oist --input /flash/MillerU/sample_trial_circRNA.csv --input_type fastq --phenotype /flash/MillerU/phenotype_circRNA.csv --outdir results_circRNA_all_working --tool ciriquant,circexplorer2,circrna_finder,dcc --module 'circrna_discovery, differential_expression' --fasta ./s_les_chr.fasta --gtf /bucket/MillerU/Zifcakova/Dovetail_ika_genomes/Dovetail_annotated_v_10_04_2022/PO1788_Sepioteuthis_lessoniana_annotation_chr1.gtf --mature /bucket/MillerU/Zifcakova/databases/mature.fa --igenomes_ignore true --adapters /home/l/lucia-zifcakova/.nextflow/assets/nf-core/circrna/bin/adapters.fa --max_cpus 40 --genome false --star /flash/MillerU/work/6d/1cbd95ce8882b4fd2e5a13deeb715d/STARIndex --fasta_fai /flash/MillerU/work/33/4c3fd667f44d34b40596f42a4c1d70/s_les_chr.fasta.fai --bwa /flash/MillerU/work/ac/6c9686383b60b3c7c986576c6dfcab/BWAIndex

**Comment by nictru** [comment]
This should be fixed since the current hisat2 version in the conda environment of the `HISAT2_ALIGN` process is `2.2.1`
