### ISSUE TITLE
Test workflow not working

### ISSUE THREAD

**Issue by guillaumecharbonnier** [nf-core/circrna#52]
Hello, 

I am unable to successfully reproduce the test workflow : 
`nextflow run nf-core/circrna -profile test,docker -r dev`

```
Error executing process > 'FASTA (fust1_1:CIRCexplorer2)'

Caused by:
  Missing output file(s) `fasta/*` expected by process `FASTA (fust1_1:CIRCexplorer2)`

Command executed:

  ## FASTA sequences (bedtools does not like the extra annotation info - split will not work properly)
  cut -d$'      ' -f1-12 fust1_1.bed > bed12.tmp
  bedtools getfasta -fi chrI.fa -bed bed12.tmp -s -split -name > circ_seq.tmp
  ## clean fasta header
  grep -A 1 '>' circ_seq.tmp | cut -d: -f1,2,3 > circ_seq.fa && rm circ_seq.tmp
  ## output to dir
  mkdir -p fasta
  awk -F '>' '/^>/ {F=sprintf("fasta/%s.fa",$2); print > F;next;} {print >> F;}' < circ_seq.fa

Command exit status:
  0

Command output:
  (empty)

Command error:
  index file chrI.fa.fai not found, generating...
```

I have also tried the master branch 
`nextflow run nf-core/circrna -profile test,docker -r master` with another error.

I have attached the log files fgor both attempts.
[nextflow.dev.log](https://github.com/nf-core/circrna/files/9415675/nextflow.dev.log)
[nextflow.master.log](https://github.com/nf-core/circrna/files/9415676/nextflow.master.log)

- Hardware: Desktop 32 threads 64 go RAM
- Executor: local
- OS: Ubuntu 22 LTS
- Nextflow: version 22.04.5.5708
- Engine: Docker version 20.10.17, build 100c701
- Image tag: https://github.com/nf-core/circrna [determined_pare] DSL1 - revision: cb41d06748 [dev]

**Comment by BarryDigby** [comment]
Hi Guillaume, 

I could not reproduce the error locally - it ran to completion with the following setup on a laptop:

* nextflow: version 22.04.4.5706
* OS: macOS Monterey 12.5.1 (21G83)
* docker: version 20.10.17, build 100c701

I have never used this laptop to run the analysis so it seems everything packaged with the workflow is working (for me).

***

Please do not use `master`, it is not stable. Try giving it another shot and let me know if the same error occurs.

**Comment by guillaumecharbonnier** [comment]
Thanks Barry,

The pipeline completed successfully on my other workstation so it narrows it down to a specific issue in my first machine.
