### ISSUE TITLE
Problem in running circrna

### ISSUE THREAD

**Issue by FeiLiuEM** [nf-core/circrna#81]
### Description of the bug

Nextflow is an excellent standardized pipeline tool and helps me a lot.

When I use the `circrna`, it always report error:

```
Execution cancelled -- Finishing pending tasks before exit
WARN: Got an interrupted exception while taking agent result | java.lang.InterruptedException
ERROR ~ Error executing process > 'NFCORE_CIRCRNA:CIRCRNA:PREPARE_GENOME:HISAT2_EXTRACTSPLICESITES'

Caused by:
  Not a valid path value: 'null'

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details
ERROR ~ Unexpected error [ClosedByInterruptException]

 -- Check '.nextflow.log' file for details
ERROR ~ Unexpected error [ClosedByInterruptException]

 -- Check '.nextflow.log' file for details
```

It doesn't seem to have read the file yet. But when I change the code to run eccdna, it works well. 

Could you please tell me why?

### Command used and terminal output

```console
$nextflow run nf-core/circrna --input samplesheet_1.csv --outdir '/media/super/Hard_Disk_1/USING/circdna/HCMV/HCMV/fastq/result' --genome GRCh38 -profile docker
```

### Relevant files

[.nextflow.log](https://github.com/nf-core/circrna/files/13034438/default.nextflow.log)

### System information

N E X T F L O W  ~  version 23.10.0
Hardware: Desktop
Executor: local
Container engine: Docker
OS: Ubuntu 22.04
version of circrna: revision: 18e580e3f8 [master]

**Comment by nictru** [comment]
Could you retry this using the dev branch? You just have to add "-r dev" to the command.

**Comment by nictru** [comment]
Closing this for now, feel free to re-open if the problems persist
