### ISSUE TITLE
Implement improved annotation of hits also in the DIFFERENTIAL_EXPRESSION:PARENT_GENE process

### ISSUE THREAD

**Issue by MariekeVromman** [nf-core/circrna#97]
Recently, @nictru updated the annotation pipeline (with #95), improving the overall performance. This should also be applied to the DIFFERENTIAL_EXPRESSION:PARENT_GENE process

**Comment by nictru** [comment]
Closing this as this will happen as part of a larger refactoring of the `DIFFERENTIAL_EXPRESSION` subworkflow
